# Generated by Django 5.1.1 on 2024-09-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('retired', models.BooleanField()),
                ('current_team', models.CharField(max_length=50, null=True)),
                ('games_played', models.IntegerField()),
                ('games_started', models.IntegerField()),
                ('minutes_played', models.IntegerField()),
                ('field_goals_made', models.IntegerField()),
                ('field_goals_attempted', models.IntegerField()),
                ('field_goal_percentage', models.FloatField()),
                ('three_pointers_made', models.IntegerField()),
                ('three_pointers_attempted', models.IntegerField()),
                ('three_point_percentage', models.FloatField()),
                ('free_throws_made', models.IntegerField()),
                ('free_throws_attempted', models.IntegerField()),
                ('free_throw_percentage', models.FloatField()),
                ('offensive_rebounds', models.IntegerField()),
                ('defensive_rebounds', models.IntegerField()),
                ('total_rebounds', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('steals', models.IntegerField()),
                ('blocks', models.IntegerField()),
                ('turnovers', models.IntegerField()),
                ('personal_fouls', models.IntegerField()),
                ('points', models.IntegerField()),
            ],
            options={
                'db_table': 'players',
            },
        ),
    ]
