# Generated by Django 5.1.1 on 2024-09-10 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='players',
            options={'managed': False},
        ),
    ]
