# Generated by Django 5.1.1 on 2024-09-10 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba_data', '0002_alter_players_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='players',
            options={},
        ),
    ]
