# Generated by Django 5.1.1 on 2024-09-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_data', '0003_alter_players_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='assists',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='blocks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='defensive_rebounds',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='field_goal_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='field_goals_attempted',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='field_goals_made',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='free_throw_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='free_throws_attempted',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='free_throws_made',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='games_played',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='games_started',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='minutes_played',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='offensive_rebounds',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='personal_fouls',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='points',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='steals',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='three_point_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='three_pointers_attempted',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='three_pointers_made',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='total_rebounds',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='turnovers',
            field=models.IntegerField(null=True),
        ),
    ]
