# Generated by Django 5.1.1 on 2024-09-10 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba_data', '0004_alter_players_assists_alter_players_blocks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='current_team',
        ),
    ]
